import { defineSchema, MatirProvider } from "@matir-js/react";
import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const matirSchema = defineSchema({
  roles: { admin: "admin" },
  actions: {
    create: "create",
    read: "read",
    update: "update",
    delete: "delete",
  },
  rules: {
    order: {
      actions: ["create", "read", "update", "delete"],
      roles: ["admin"],
      sub: {
        export: {
          actions: ["create", "read", "update", "delete"],
          roles: ["admin"],
        },
      },
    },
  },
});

declare module "@matir-js/react" {
  interface MatirRegister {
    schema: typeof matirSchema;
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <MatirProvider schema={matirSchema}>
        <body className="min-h-full flex flex-col">{children}</body>
      </MatirProvider>
    </html>
  );
}
